[package]
name = "fractal-lawyer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fractal-lawyer"
path = "src/main.rs"

[dependencies]
ed25519-dalek.workspace = true
rand = "0.8"
hex = "0.4"
async-io = "2"
zbus = { workspace = true, features = ["async-io"] }
serde = { workspace = true, features = ["derive"] }
