//! The configuration the agent owns, held as structured data and projected to a
//! Nix file through one pure serializer. The file is never edited as text: an
//! edit reads the model, sets one key, and re-serializes the whole thing, so the
//! same model always produces the same bytes and the git history carries only
//! real changes. This totality is why written values are restricted to plain
//! data — no functions, let-bindings, or imports.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// A plain-data value. This is the whole vocabulary the agent may write into the
/// configuration; anything expressive lives in human-authored modules the agent
/// never touches. `untagged` so it round-trips with the JSON that `nix eval`
/// emits when reading current values.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Value {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Str(String),
    List(Vec<Value>),
    Attrs(BTreeMap<String, Value>),
}

/// The agent-owned option model: a map from a real NixOS option path (e.g.
/// `networking.hostName`) to its plain-data value. `BTreeMap` fixes iteration
/// order, which is half of what makes serialization canonical.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Model {
    options: BTreeMap<String, Value>,
}

impl Model {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn get(&self, key: &str) -> Option<&Value> {
        self.options.get(key)
    }

    /// The whole option map, for comparing two models with [`crate::diff`].
    pub fn options(&self) -> &BTreeMap<String, Value> {
        &self.options
    }

    /// Set one option. Returns the previous value if the key was already set.
    pub fn set(&mut self, key: impl Into<String>, value: Value) -> Option<Value> {
        self.options.insert(key.into(), value)
    }

    pub fn remove(&mut self, key: &str) -> Option<Value> {
        self.options.remove(key)
    }

    pub fn iter(&self) -> impl Iterator<Item = (&String, &Value)> {
        self.options.iter()
    }

    pub fn is_empty(&self) -> bool {
        self.options.is_empty()
    }

    /// Reconstruct the model from the JSON that evaluating the generated module
    /// yields: a nested attrset of plain data. Object keys are joined with dots
    /// down to each non-object leaf, inverting the dotted definitions `to_nix`
    /// emits. This is the pure half of reading the overlay back; a caller
    /// evaluates the module to JSON, this turns it into a model.
    ///
    /// The recursion descends every attrset, so an option whose *value* is an
    /// attrset would be flattened past its own boundary. The curated catalog
    /// therefore holds only scalar- and list-valued options, for which the round
    /// trip is exact.
    pub fn from_eval_json(json: &serde_json::Value) -> Self {
        let mut options = BTreeMap::new();
        flatten("", json, &mut options);
        Self { options }
    }

    /// Project the whole model to a canonical NixOS module. Pure function of the
    /// model: identical models yield byte-identical output.
    pub fn to_nix(&self) -> String {
        let mut out = String::new();
        out.push_str("# Generated by fractal-agent — do not edit by hand.\n");
        out.push_str("{ ... }:\n");
        if self.options.is_empty() {
            out.push_str("{ }\n");
            return out;
        }
        out.push_str("{\n");
        for (key, value) in &self.options {
            out.push_str("  ");
            out.push_str(key);
            out.push_str(" = ");
            write_value(&mut out, value, 1);
            out.push_str(";\n");
        }
        out.push_str("}\n");
        out
    }
}

/// Join object keys with dots down to each non-object leaf, inverting the dotted
/// definitions in [`Model::to_nix`].
fn flatten(prefix: &str, json: &serde_json::Value, out: &mut BTreeMap<String, Value>) {
    match json {
        serde_json::Value::Object(map) => {
            for (key, value) in map {
                let path = if prefix.is_empty() {
                    key.clone()
                } else {
                    format!("{prefix}.{key}")
                };
                flatten(&path, value, out);
            }
        }
        leaf => {
            out.insert(prefix.to_string(), json_to_value(leaf));
        }
    }
}

/// Convert one evaluated JSON value to a plain-data [`Value`]. A number is an
/// integer when it fits, else a float; nested objects (inside a list leaf) map
/// to attrs.
fn json_to_value(json: &serde_json::Value) -> Value {
    use serde_json::Value as J;
    match json {
        J::Null => Value::Null,
        J::Bool(b) => Value::Bool(*b),
        J::Number(n) => n
            .as_i64()
            .map(Value::Int)
            .unwrap_or_else(|| Value::Float(n.as_f64().unwrap_or(0.0))),
        J::String(s) => Value::Str(s.clone()),
        J::Array(items) => Value::List(items.iter().map(json_to_value).collect()),
        J::Object(map) => {
            Value::Attrs(map.iter().map(|(k, v)| (k.clone(), json_to_value(v))).collect())
        }
    }
}

fn write_value(out: &mut String, value: &Value, indent: usize) {
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        Value::Int(n) => out.push_str(&n.to_string()),
        // `{:?}` keeps a decimal point so a float never serializes as an int.
        Value::Float(f) => out.push_str(&format!("{f:?}")),
        Value::Str(s) => write_string(out, s),
        Value::List(items) => {
            if items.is_empty() {
                out.push_str("[ ]");
                return;
            }
            out.push_str("[\n");
            let pad = "  ".repeat(indent + 1);
            for item in items {
                out.push_str(&pad);
                write_value(out, item, indent + 1);
                out.push('\n');
            }
            out.push_str(&"  ".repeat(indent));
            out.push(']');
        }
        Value::Attrs(attrs) => {
            if attrs.is_empty() {
                out.push_str("{ }");
                return;
            }
            out.push_str("{\n");
            let pad = "  ".repeat(indent + 1);
            for (k, v) in attrs {
                out.push_str(&pad);
                write_attr_name(out, k);
                out.push_str(" = ");
                write_value(out, v, indent + 1);
                out.push_str(";\n");
            }
            out.push_str(&"  ".repeat(indent));
            out.push('}');
        }
    }
}

/// A Nix double-quoted string with every `$` escaped, so a staged string value
/// can never open an interpolation (`${...}`) or otherwise escape into the
/// expression. This is the config-layer form of "staged values are plain data".
fn write_string(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
}

/// Emit an attribute name, quoting it unless it is a bare Nix identifier.
fn write_attr_name(out: &mut String, name: &str) {
    let bare = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-' || c == '\'')
        && !name.chars().next().unwrap().is_ascii_digit();
    if bare {
        out.push_str(name);
    } else {
        write_string(out, name);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn attrs(pairs: &[(&str, Value)]) -> Value {
        Value::Attrs(pairs.iter().map(|(k, v)| (k.to_string(), v.clone())).collect())
    }

    #[test]
    fn empty_model() {
        assert_eq!(
            Model::new().to_nix(),
            "# Generated by fractal-agent — do not edit by hand.\n{ ... }:\n{ }\n"
        );
    }

    #[test]
    fn canonical_and_deterministic() {
        let mut a = Model::new();
        a.set("networking.hostName", Value::Str("box".into()));
        a.set("networking.firewall.enable", Value::Bool(true));
        a.set("time.timeZone", Value::Str("UTC".into()));

        // Insertion order must not matter: same options, different order, same bytes.
        let mut b = Model::new();
        b.set("time.timeZone", Value::Str("UTC".into()));
        b.set("networking.hostName", Value::Str("box".into()));
        b.set("networking.firewall.enable", Value::Bool(true));

        assert_eq!(a.to_nix(), b.to_nix());
        assert_eq!(
            a.to_nix(),
            "# Generated by fractal-agent — do not edit by hand.\n\
             { ... }:\n\
             {\n  \
               networking.firewall.enable = true;\n  \
               networking.hostName = \"box\";\n  \
               time.timeZone = \"UTC\";\n\
             }\n"
        );
    }

    #[test]
    fn escapes_interpolation_and_quotes() {
        let mut m = Model::new();
        m.set("services.foo.motd", Value::Str("hi ${IFS} \"x\" \\ end".into()));
        let out = m.to_nix();
        assert!(out.contains(r#"= "hi \${IFS} \"x\" \\ end";"#), "got: {out}");
    }

    #[test]
    fn nested_list_and_attrs() {
        let mut m = Model::new();
        m.set(
            "services.x.settings",
            attrs(&[
                ("ports", Value::List(vec![Value::Int(22), Value::Int(80)])),
                ("names", Value::List(vec![])),
            ]),
        );
        let out = m.to_nix();
        assert!(out.contains("ports = [\n"), "got: {out}");
        assert!(out.contains("names = [ ];"), "got: {out}");
    }

    #[test]
    fn from_eval_json_flattens_nested_attrs_to_dotted_keys() {
        // The shape `nix eval` emits for an evaluated module body.
        let json = serde_json::json!({
            "networking": {
                "hostName": "box",
                "firewall": { "enable": true, "allowedTCPPorts": [22, 80] }
            },
            "time": { "timeZone": "UTC" },
            "boot": { "loader": { "timeout": 5 } }
        });
        let m = Model::from_eval_json(&json);
        assert_eq!(m.get("networking.hostName"), Some(&Value::Str("box".into())));
        assert_eq!(m.get("networking.firewall.enable"), Some(&Value::Bool(true)));
        assert_eq!(
            m.get("networking.firewall.allowedTCPPorts"),
            Some(&Value::List(vec![Value::Int(22), Value::Int(80)]))
        );
        assert_eq!(m.get("time.timeZone"), Some(&Value::Str("UTC".into())));
        assert_eq!(m.get("boot.loader.timeout"), Some(&Value::Int(5)));
    }

    #[test]
    fn from_eval_json_inverts_to_nix_for_leaf_options() {
        // A model of scalar and list options survives the projection-and-read
        // round trip: `from_eval_json` recovers exactly what a model set, given
        // the evaluated form of what `to_nix` wrote.
        let mut m = Model::new();
        m.set("networking.hostName", Value::Str("box".into()));
        m.set("networking.firewall.enable", Value::Bool(true));
        m.set("networking.firewall.allowedTCPPorts", Value::List(vec![Value::Int(22)]));
        m.set("time.timeZone", Value::Str("UTC".into()));

        // Nested JSON is what evaluating the generated module would yield.
        let evaluated = serde_json::json!({
            "networking": {
                "hostName": "box",
                "firewall": { "enable": true, "allowedTCPPorts": [22] }
            },
            "time": { "timeZone": "UTC" }
        });
        assert_eq!(Model::from_eval_json(&evaluated), m);
    }

    #[test]
    fn from_eval_json_empty_body_is_empty_model() {
        assert!(Model::from_eval_json(&serde_json::json!({})).is_empty());
    }

    #[test]
    fn value_round_trips_through_json() {
        let v = attrs(&[
            ("a", Value::Bool(true)),
            ("b", Value::Int(7)),
            ("c", Value::Str("s".into())),
            ("d", Value::List(vec![Value::Float(1.5), Value::Null])),
        ]);
        let json = serde_json::to_string(&v).unwrap();
        let back: Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v, back);
    }
}
