//! The configuration the agent owns, held as structured data and projected to a
//! Nix file through one pure serializer. The file is never edited as text: an
//! edit reads the model, sets one key, and re-serializes the whole thing, so the
//! same model always produces the same bytes and the git history carries only
//! real changes. This totality is why written values are restricted to plain
//! data — no functions, let-bindings, or imports.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// A plain-data value. This is the whole vocabulary the agent may write into the
/// configuration; anything expressive lives in human-authored modules the agent
/// never touches. `untagged` so it round-trips with the JSON that `nix eval`
/// emits when reading current values.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Value {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Str(String),
    List(Vec<Value>),
    Attrs(BTreeMap<String, Value>),
}

/// The agent-owned option model: a map from a real NixOS option path (e.g.
/// `networking.hostName`) to its plain-data value. `BTreeMap` fixes iteration
/// order, which is half of what makes serialization canonical.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Model {
    options: BTreeMap<String, Value>,
}

impl Model {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn get(&self, key: &str) -> Option<&Value> {
        self.options.get(key)
    }

    /// Set one option. Returns the previous value if the key was already set.
    pub fn set(&mut self, key: impl Into<String>, value: Value) -> Option<Value> {
        self.options.insert(key.into(), value)
    }

    pub fn remove(&mut self, key: &str) -> Option<Value> {
        self.options.remove(key)
    }

    pub fn iter(&self) -> impl Iterator<Item = (&String, &Value)> {
        self.options.iter()
    }

    pub fn is_empty(&self) -> bool {
        self.options.is_empty()
    }

    /// Project the whole model to a canonical NixOS module. Pure function of the
    /// model: identical models yield byte-identical output.
    pub fn to_nix(&self) -> String {
        let mut out = String::new();
        out.push_str("# Generated by fractal-agent — do not edit by hand.\n");
        out.push_str("{ ... }:\n");
        if self.options.is_empty() {
            out.push_str("{ }\n");
            return out;
        }
        out.push_str("{\n");
        for (key, value) in &self.options {
            out.push_str("  ");
            out.push_str(key);
            out.push_str(" = ");
            write_value(&mut out, value, 1);
            out.push_str(";\n");
        }
        out.push_str("}\n");
        out
    }
}

fn write_value(out: &mut String, value: &Value, indent: usize) {
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        Value::Int(n) => out.push_str(&n.to_string()),
        // `{:?}` keeps a decimal point so a float never serializes as an int.
        Value::Float(f) => out.push_str(&format!("{f:?}")),
        Value::Str(s) => write_string(out, s),
        Value::List(items) => {
            if items.is_empty() {
                out.push_str("[ ]");
                return;
            }
            out.push_str("[\n");
            let pad = "  ".repeat(indent + 1);
            for item in items {
                out.push_str(&pad);
                write_value(out, item, indent + 1);
                out.push('\n');
            }
            out.push_str(&"  ".repeat(indent));
            out.push(']');
        }
        Value::Attrs(attrs) => {
            if attrs.is_empty() {
                out.push_str("{ }");
                return;
            }
            out.push_str("{\n");
            let pad = "  ".repeat(indent + 1);
            for (k, v) in attrs {
                out.push_str(&pad);
                write_attr_name(out, k);
                out.push_str(" = ");
                write_value(out, v, indent + 1);
                out.push_str(";\n");
            }
            out.push_str(&"  ".repeat(indent));
            out.push('}');
        }
    }
}

/// A Nix double-quoted string with every `$` escaped, so a staged string value
/// can never open an interpolation (`${...}`) or otherwise escape into the
/// expression. This is the config-layer form of "staged values are plain data".
fn write_string(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
}

/// Emit an attribute name, quoting it unless it is a bare Nix identifier.
fn write_attr_name(out: &mut String, name: &str) {
    let bare = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-' || c == '\'')
        && !name.chars().next().unwrap().is_ascii_digit();
    if bare {
        out.push_str(name);
    } else {
        write_string(out, name);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn attrs(pairs: &[(&str, Value)]) -> Value {
        Value::Attrs(pairs.iter().map(|(k, v)| (k.to_string(), v.clone())).collect())
    }

    #[test]
    fn empty_model() {
        assert_eq!(
            Model::new().to_nix(),
            "# Generated by fractal-agent — do not edit by hand.\n{ ... }:\n{ }\n"
        );
    }

    #[test]
    fn canonical_and_deterministic() {
        let mut a = Model::new();
        a.set("networking.hostName", Value::Str("box".into()));
        a.set("networking.firewall.enable", Value::Bool(true));
        a.set("time.timeZone", Value::Str("UTC".into()));

        // Insertion order must not matter: same options, different order, same bytes.
        let mut b = Model::new();
        b.set("time.timeZone", Value::Str("UTC".into()));
        b.set("networking.hostName", Value::Str("box".into()));
        b.set("networking.firewall.enable", Value::Bool(true));

        assert_eq!(a.to_nix(), b.to_nix());
        assert_eq!(
            a.to_nix(),
            "# Generated by fractal-agent — do not edit by hand.\n\
             { ... }:\n\
             {\n  \
               networking.firewall.enable = true;\n  \
               networking.hostName = \"box\";\n  \
               time.timeZone = \"UTC\";\n\
             }\n"
        );
    }

    #[test]
    fn escapes_interpolation_and_quotes() {
        let mut m = Model::new();
        m.set("services.foo.motd", Value::Str("hi ${IFS} \"x\" \\ end".into()));
        let out = m.to_nix();
        assert!(out.contains(r#"= "hi \${IFS} \"x\" \\ end";"#), "got: {out}");
    }

    #[test]
    fn nested_list_and_attrs() {
        let mut m = Model::new();
        m.set(
            "services.x.settings",
            attrs(&[
                ("ports", Value::List(vec![Value::Int(22), Value::Int(80)])),
                ("names", Value::List(vec![])),
            ]),
        );
        let out = m.to_nix();
        assert!(out.contains("ports = [\n"), "got: {out}");
        assert!(out.contains("names = [ ];"), "got: {out}");
    }

    #[test]
    fn value_round_trips_through_json() {
        let v = attrs(&[
            ("a", Value::Bool(true)),
            ("b", Value::Int(7)),
            ("c", Value::Str("s".into())),
            ("d", Value::List(vec![Value::Float(1.5), Value::Null])),
        ]);
        let json = serde_json::to_string(&v).unwrap();
        let back: Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v, back);
    }
}
